### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by muziling** [EvilCult/iptv-m3u-maker#27]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/muziling/my/iptv-m3u-maker/plugins/dotpy.py", line 50, in detectData
    self.addData(data)
  File "/home/muziling/my/iptv-m3u-maker/plugins/dotpy.py", line 62, in addData
    DB.insert(data)
  File "/home/muziling/my/iptv-m3u-maker/db.py", line 68, in insert
    self.cur.execute(sql)
sqlite3.OperationalError: database is locked

**Comment by sztoddwong** [comment]
Traceback (most recent call last):
  File "D:/python-code/iptv-m3u-maker-master/main.py", line 106, in <module>
    obj.run()
  File "D:/python-code/iptv-m3u-maker-master/main.py", line 25, in run
    Dotpy.getSource()
  File "D:\python-code\iptv-m3u-maker-master\plugins\dotpy.py", line 19, in getSource
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 8: illegal multibyte sequence

Process finished with exit code 1

**Comment by EvilCult** [comment]
本次更新已解决这个问题!
