### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by foxling** [EvilCult/iptv-m3u-maker#31]
docker 中运行过程中一直报 `sqlite3.OperationalError: database is locked`，这个影响结果吗？

```
Checking[ 亳州新闻频道 ]: http://218.22.251.12:8001/tslslive/wT9aUpL/hls/live_sd.m3u8
Exception in thread Thread-1828:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/myapp/plugins/dotpy.py", line 50, in detectData
    self.addData(data)
  File "/usr/src/myapp/plugins/dotpy.py", line 62, in addData
    DB.insert(data)
  File "/usr/src/myapp/db.py", line 68, in insert
    self.cur.execute(sql)
sqlite3.OperationalError: database is locked
```

**Comment by EvilCult** [comment]
有影响,本次更新已解决这个问题!
