### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by cuteJaven** [EvilCult/iptv-m3u-maker#50]
我是个小白，不太懂是不是自己哪一步操作失误了···
用的Windows 10系统，今天刚装了python、git，配置好了环境变量，然后用命令行执行所给的三行命令，第三行命令运行出错，错误内容如下
Traceback (most recent call last):
  File "iptv.py", line 110, in <module>
    obj.run()
  File "iptv.py", line 30, in run
    Dotpy.getSource()
  File "C:\Users\10718\Desktop\iptv-m3u-maker-master\iptv-m3u-maker\python\plugins\dotpy.py", line 20, in getSource
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 8: illegal multibyte sequence

**Comment by EvilCult** [comment]
Duplicate of #33 

不是你的锅.......
小白建议等下一个版本...彻底基于Docker部署.....力争拷贝两行代码搞定所有问题....

但是游戏机太好玩了我也不能保证什么时候放出...可关注dev分支实时督促.......
